
name: CI

on:
  push:
    branches: [ main ]


jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Install packages
        run: yarn
      - name: Run build
        run: NODE_OPTIONS="--max-old-space-size=4096" CI=false GENERATE_SOURCEMAP=false npm run build --if-present

      # Runs a set of commands using the runners shell
      - name: Reload server
        run: pm2 reload all
